{% set version = "2.2.3" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-genius
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/genius_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/genius/genius_{{ version }}.tar.gz
  sha256: 1e2f23facb8b635a9e29f44f2adf3181b76c860f5d729b195bc8da347cf6460e

build:
  merge_build_host: true  # [win]
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-dplyr >=0.7.0
    - r-purrr
    - r-readr
    - r-reshape2
    - r-rvest
    - r-stringr
    - r-tibble
    - r-tidyr
    - r-tidytext
  run:
    - r-base
    - r-dplyr >=0.7.0
    - r-purrr
    - r-readr
    - r-reshape2
    - r-rvest
    - r-stringr
    - r-tibble
    - r-tidyr
    - r-tidytext

test:
  commands:
    - $R -e "library('genius')"           # [not win]
    - "\"%R%\" -e \"library('genius')\""  # [win]

about:
  home: https://github.com/josiahparry/genius
  license: GPL-2.0-only
  summary: Easily access song lyrics in a tidy way.
  license_family: GPL2
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: genius
# Title: Easily Access Song Lyrics from Genius.com
# Version: 2.2.0
# Authors@R: c( person("Josiah", "Parry", email = "josiah.parry@gmail.com", role = c("aut", "cre")), person("Nathan", "Barr", email = "nab222@cornell.edu", role = "ctb") )
# Description: Easily access song lyrics in a tidy way.
# URL: https://github.com/josiahparry/genius
# BugReports: https://github.com/josiahparry/genius/issues
# Depends: R (>= 3.1.2)
# Imports: dplyr (>= 0.7.0), rvest, stringr, tidyr, purrr, readr, tibble, tidytext, reshape2
# License: GPL-2
# Encoding: UTF-8
# LazyData: true
# RoxygenNote: 6.1.1
# Suggests: knitr, rmarkdown, testthat
# NeedsCompilation: no
# Packaged: 2019-05-05 20:50:57 UTC; josiah
# Author: Josiah Parry [aut, cre], Nathan Barr [ctb]
# Maintainer: Josiah Parry <josiah.parry@gmail.com>
# Repository: CRAN
# Date/Publication: 2019-05-05 21:10:03 UTC
