appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: UziEyDGlLNhQVJTmhddGzoKUCIWypJiyAFKtTLSpbPVhvbjfIQoHSPA6Ml4RG/pqmLXlyOqFuJe6n4lpU8AeaoPolH0M5DH97ux7PDXjejq+nNN0yAEfSgcRg6lLBBrFfRfkTbqb/dcjhCxhA0tQnsA/+MSUP5zJTDFxQmy23EJcnKx18cXnanRUORMH43bmI8uiHOA+QJ9zE3euqkn+3jaWCP2R1wlomsYH18LQ18e10jB/pqEFOpzIrKW8ITbycpXuT8rNRmbLLPaINxVzvXz+ohrBnMkoBuMYd+VziIgPy2qY/BhMbI7ct1rIHauAVAdg1JU1sUPrGYraeru0pCNj3xERvab8JtqesdHeNBaQdPVJ8Q/phYO/+t+gF+xydClraNbelxNC0ibT+Vyb+HEPXoRiHxkYEXHKVP2vDq5lYgUY0NXRpZzU4b3Za/6JAUEJgVjGLK2+MmlN2+149bsKyddO5r8Dl6UQeah5U3KMK9wm6nPN/3LiVV360nrrBhWUDm1xKTkiKzkR4JBt4dS+j4yhnqH8M4NN85nyGvSKOhJLStJIgdJiZwSlUCGIkmnttPLdWIyFPscPMOZhVd4fbLFV4sa6BaprH9yHR0c2reazUKyB2kdBHrkKjMhnayEry12IqURPNdedSGo/y8TyPRR+I5oKspo0EPJdSPc=}
bot:
  automerge: true
